# Esercitazione "Laboratorio di Programmazione Geometrica e Grafica"

## Workshop_00 (16-10-17)
- In questo workshop sono stati fatti i primi esperimenti con PyPlasm e LarLiB utilizzando la documentazione disponibile
- Sono stati svolti i due esercizi assegnati dal professore

### Primi passi con Jupyter Notebook

Comando per importare la libreria pyplasm

In [1]:
from pyplasm import *

Evaluating fenvs.py..
...fenvs.py imported in 0.00750972839506 seconds


Primo comando di test per verificare il corretto caricamento della libreria Pyplasm

In [4]:
c=CUBOID([1,1,1])
VIEW(c)

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BA83BD0> >

### Primi esperimenti con la libreria Numpy

Comando per importare la libreria numpy e richiamarlo con "np"

In [2]:
import numpy as np

Creazione di un array e stampa del risultato

In [6]:
a = np.array([2,3,4])

In [7]:
a

array([2, 3, 4])

Stampa del tipo

In [8]:
a.dtype

dtype('int32')

<b>Creazione di un array di array</b> e stampa

In [9]:
b = np.array([(1,2,3), (4,5,6)])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

Utilizzo di <b>zeros</b>, <b>ones</b> e <b>empty</b> per creare array con tutti zeri, uno o random

In [14]:
np.zeros( (3), dtype=np.int16 )

array([0, 0, 0], dtype=int16)

In [15]:
np.ones( (3), dtype=np.int16 )

array([1, 1, 1], dtype=int16)

In [17]:
np.empty( (3), dtype=np.float64)

array([  0.00000000e+000,   4.94065646e-324,   9.88131292e-324])

Uitizzo di <b>arange</b> per creare un array contenente una sequenza di numeri (in questo caso da 10 a 100 in multipli di 3)

In [18]:
np.arange( 10, 100, 3 )

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

Utilizzo di <b>linspace</b> per creare un array con un determinato numero di elementi equidistanti compresi tra due estremi

In [26]:
np.linspace( 1, 100, 4 )

array([   1.,   34.,   67.,  100.])

Utilizzo della funzione <b>random</b> (la quale restituisce un valore compreso tra 0 e 1) per creare una matrice 10x10

In [27]:
np.random.rand(10,10)

array([[ 0.12875223,  0.09196126,  0.55565574,  0.0940437 ,  0.2666141 ,
         0.93679405,  0.11740822,  0.1858369 ,  0.50312107,  0.30848159],
       [ 0.52619382,  0.74544073,  0.90744984,  0.49285165,  0.65214861,
         0.97124349,  0.18255918,  0.89726188,  0.26984543,  0.50794325],
       [ 0.62699755,  0.53653709,  0.08774499,  0.90187527,  0.055806  ,
         0.94083739,  0.50021498,  0.46731872,  0.75478119,  0.33791637],
       [ 0.86730645,  0.45499836,  0.86233367,  0.13096835,  0.35465273,
         0.74800564,  0.90779364,  0.39397568,  0.13172283,  0.50642018],
       [ 0.42737988,  0.87302821,  0.95227696,  0.10906536,  0.7394893 ,
         0.19414796,  0.64212448,  0.28367519,  0.22889478,  0.89393825],
       [ 0.72828412,  0.26461998,  0.76721839,  0.09388596,  0.18062075,
         0.20452132,  0.52674838,  0.62806317,  0.95025764,  0.36816433],
       [ 0.15774014,  0.92122695,  0.84656466,  0.84631659,  0.55273589,
         0.42929855,  0.74505315,  0.59322574

Utilizzo delle funzioni <b>arange</b> e <b>reshape</b>. Con arange si definisce la sequenza di numeri da inserire nell'array, mentre in reshape(a,b) "a" indica il numero di righe e "b" il numero di colonne

In [30]:
b = np.arange(30).reshape(6,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


<h4>Operazioni sugli array</h4>

Creazione di due array di 4 elementi e <b>somma degli elementi degli array</b>

In [39]:
a = np.array( [0,5,10,15] )
b = np.arange( 4 )
print (a)
print (b)
c = a + b
print (c)

[ 0  5 10 15]
[0 1 2 3]
[ 0  6 12 18]


Creazione di due array di 4 elementi e <b>sottrazione tra due array</b>

In [103]:
a = np.array( [0,5,10,15] )
b = np.arange( 4 )
print (a)
print (b)
c = a - b
print (c)

[ 0  5 10 15]
[0 1 2 3]
[ 0  4  8 12]


Calcolare il <b>quadrato di un array</b>

In [50]:
d = np.arange( 4 )
print (d)
d = d**2
print (d)

[0 1 2 3]
[0 1 4 9]


Creazione di un <b>array di booleani</b> mediante la verifica di una condizione (in questo esempio "elemento<5") su un altro array

In [54]:
e = np.arange( 10 )
f=e<5
print (f)

[ True  True  True  True  True False False False False False]


<b>Prodotto tra gli elementi di due matrici</b>

In [58]:
a = np.array ([[1,2],[3,4]])
b = np.array ([[1,2],[3,4]])
c = a*b
print (c)

[[ 1  4]
 [ 9 16]]


<b>Prodotto tra matrici</b>

In [59]:
a = np.array ([[1,2],[3,4]])
b = np.array ([[1,2],[3,4]])
c = a.dot(b)
print (c)

[[ 7 10]
 [15 22]]


Funzioni <b>sum</b>, <b>min</b> e <b>max</b>

In [75]:
a = np.random.random((5,5))
print (a)
e1 = a.sum()
e2 = a.min()
e3 = a.max()
print
print(e1, e2, e3)

[[ 0.04890965  0.50130282  0.20509301  0.14815001  0.5026256 ]
 [ 0.26620318  0.43218966  0.67845471  0.35393778  0.30992877]
 [ 0.87361943  0.55116971  0.58310095  0.0887389   0.75510828]
 [ 0.90633922  0.12286624  0.88731421  0.19849689  0.28791601]
 [ 0.40254901  0.6702907   0.75505998  0.10275666  0.5044753 ]]

(11.136596678308937, 0.048909654650350576, 0.90633921681823815)


Calcolo della <b>somma</b>, del <b>minimo</b> e del <b>massimo per ogni colonna</b>

In [84]:
a = np.arange(25).reshape((5,5))
print (a)
print
print (a.sum(axis=0))
print (a.min(axis=1))
print (a.max(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[50 55 60 65 70]
[ 0  5 10 15 20]
[20 21 22 23 24]


Elementi dell'array attraverso l'<b>indice</b>

In [97]:
a = np.arange(25)
print (a)
print
print ('Elemento in posizione 4:')
print (a[4])
print
print ('Elementi dalla posizione 5 (inclusa) alla posizione 10 (esclusa):')
print (a[5:10])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Elemento in posizione 4:
4

Elementi dalla posizione 5 (inclusa) alla posizione 10 (esclusa):
[5 6 7 8 9]


<b>Modifica degli elementi di un array</b> attraverso l'indice

In [101]:
a = np.arange(25)
print (a)
print
print ('Sostituzione degli elementi con indice compreso da 10 e 14 con il valore 0')
a[10:15] = 0
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Sostituzione degli elementi con indice compreso da 10 e 14 con il valore 0
[ 0  1  2  3  4  5  6  7  8  9  0  0  0  0  0 15 16 17 18 19 20 21 22 23 24]


Calcolo del <b>quadrato</b> di tutti gli elementi di un <b>array</b>

In [3]:
a = np.arange(25)
print (a)
print
for i in a:
    print(i**2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

0
1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400
441
484
529
576


Calcolo dell'<b>utima riga di una matrice</b>

In [107]:
a = np.random.random((3,3))
print
print (a)
print
print (a[-1])


[[ 0.18814771  0.26795854  0.66093916]
 [ 0.87383713  0.44684414  0.6831697 ]
 [ 0.81401059  0.33409866  0.16394424]]

[ 0.81401059  0.33409866  0.16394424]


Utilizzo della funzione <b>resize</b> per ridimensionare un array

In [110]:
a = np.random.random((4,4))
print (a)
print
a.resize((2,8))
print (a)

[[ 0.63764789  0.9477356   0.50821167  0.31876446]
 [ 0.27433692  0.73807074  0.70854302  0.13036223]
 [ 0.9959916   0.42697621  0.57237974  0.87839764]
 [ 0.45797812  0.86776658  0.02734538  0.63542264]]

[[ 0.63764789  0.9477356   0.50821167  0.31876446  0.27433692  0.73807074
   0.70854302  0.13036223]
 [ 0.9959916   0.42697621  0.57237974  0.87839764  0.45797812  0.86776658
   0.02734538  0.63542264]]


Ordinamento degli elementi delle righe di una matrice tramite <b>quicksort</b>

In [115]:
 a = np.array([[1,16,5,34,5,12],[3,1,9,22,40,19]])
print (a)
print
a = np.sort(a, kind='quicksort')
print (a)

[[ 1 16  5 34  5 12]
 [ 3  1  9 22 40 19]]

[[ 1  5  5 12 16 34]
 [ 1  3  9 19 22 40]]


## Esercizi assegnati dal Professore

- <b>Esercizio 1</b>: "Produce (and draw) 100 random points within the unit square [0,1]^2"

- <b>Spiegazione</b>: ho creato un array di coppie di elementi con valori compresi tra 0 e 1, poi li ho visualizzati nel piano.

In [3]:
from larlib import *
rn = [np.random.random(2) for i in np.arange(100)]
print (rn)
VIEW(STRUCT(map(MK,rn)))

[array([ 0.96834434,  0.74044473]), array([ 0.5233839 ,  0.39530406]), array([ 0.34933292,  0.67387442]), array([ 0.88472361,  0.6479345 ]), array([ 0.21824388,  0.81097086]), array([ 0.06226833,  0.08261826]), array([ 0.53772783,  0.43893965]), array([ 0.07476462,  0.23554313]), array([ 0.64273652,  0.78063425]), array([ 0.46032035,  0.55080354]), array([ 0.66509469,  0.59251817]), array([ 0.50690532,  0.54950324]), array([ 0.61181613,  0.08771744]), array([ 0.20919352,  0.08883586]), array([ 0.85598283,  0.95633105]), array([ 0.0058207 ,  0.65199846]), array([ 0.4689459 ,  0.18380682]), array([ 0.23652719,  0.35641025]), array([ 0.13342948,  0.87197334]), array([ 0.74565812,  0.91394832]), array([ 0.78134866,  0.78339966]), array([ 0.25313884,  0.27475848]), array([ 0.09477334,  0.05794131]), array([ 0.88901163,  0.07478975]), array([ 0.58928303,  0.09386166]), array([ 0.72949563,  0.02858199]), array([ 0.24998609,  0.12467524]), array([ 0.90767563,  0.53458016]), array([ 0.23179007,

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B792E10> >

![Screenshot%20%2820%29.png](Screenshot%20%2820%29.png)

- <b>Esercizio 2</b>: "Produce (and draw) 1000 random points within S 1 , the 1D sphere(circle) of unit radius centered at the origin (0,0)"


- <b>Spiegazione</b>: ho creato due array x e y di 1000 elementi contenenti le coordinate dei punti sul piano. Poi ho preso, per ogni i (con i che va da 0 a 999), gli elementi x[i] e y[i] degli array per rappresentare un punto sul piano.

In [3]:
from larlib import *
x = [np.random.uniform(-1,1) for i in np.arange(1000)]
y = [np.random.uniform(-sqrt(1-x[i]**2), sqrt(1-x[i]**2)) for i in np.arange(1000)]
VIEW(STRUCT(map(MK,[([ x[i],  y[i]]) for i in np.arange(1000)])))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BB79DB0> >

- Soluzione alternativa

In [2]:
from larlib import *
from random import random as rand
points = [[2*PI*rand(),rand()] for k in range(1000)]
V = [[SQRT(r)*COS(alpha),SQRT(r)*SIN(alpha)] for alpha,r in points]
cells = [[k+1] for k,v in enumerate(V)]
VIEW(MKPOL([V,cells,None]))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B917BA0> >

![Screenshot%20%2821%29.png](Screenshot%20%2821%29.png)

<h3>Primi esempi con LarLib</h3>

Comando per importare la <b>libreria LarLib</b>

In [2]:
from larlib import *

Creazione di un simplesso

In [116]:
simplices = [[1,2,4],[2,4,5],[2,3,5]]
larSimplexFacets(simplices)

[(1, 2), (1, 4), (2, 3), (2, 4), (2, 5), (3, 5), (4, 5)]

<b>Creazione di un modello</b> per mezzo di un insieme di faccie e di vertici e visualizzazione della sua struttura

In [6]:
simplices = [[1,2,4],[2,4,5],[2,3,5]]
V = [[0,0], [0,1],[2,0],[4,0],[1.5,3],[3.5,2.5]]
FV = simplices
model = V,FV
VIEW(STRUCT(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B807330> >

Comando che visualizza lo <b>scheletro del modello</b> precedentemente creato. Poi viene visualizzato.

In [6]:
VIEW(SKEL_1(STRUCT(MKPOLS(model))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B870810> >

Utilizzo del comando <b>larExtrude1</b> per estrudere un poligono a partire da modello e pattern

In [8]:
model = [[0,0],[1,0],[0,1]], [[0,1,2]]
pattern = [1]
larExtrude1(model,pattern)
VIEW(STRUCT(MKPOLS((larExtrude1(model,pattern)))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B8074B0> >

![Screenshot%20%2823%29.png](Screenshot%20%2823%29.png)

Utilizzo dell'istruzione <b>pattern = [1]*10</b> per moltiplicare per 10 il pattern

In [8]:
model = [[0,0],[1,0],[0,1]], [[0,1,2]]
pattern = [1]*10
VIEW(STRUCT(MKPOLS((larExtrude1(model,pattern)))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B891780> >

Comando per visualizzare lo scheletro della struttura precedente

In [3]:
model = [[0,0],[1,0],[0,1]], [[0,1,2]]
pattern = [1]*10
VIEW(SKEL_1((STRUCT(MKPOLS((larExtrude1(model,pattern)))))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B628600> >

Esempio di una possibile applicazione delle funzioni precedentemente viste

In [5]:
simplices = [[1,2,4],[2,4,5],[2,3,5]]
V = [[0,0], [0,1],[2,0],[4,0],[1.5,3],[3.5,2.5]]
FV = simplices
VIEW(EXPLODE(1.2,1.2,1.2)(AA(SKEL_1)(MKPOLS(larExtrude1((V,FV),[1]*10)))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B7920F0> >

![Screenshot%20%2822%29.png](Screenshot%20%2822%29.png)