# Lezione "Laboratorio di Programmazione Geometrica e Grafica"

## 03-11-17

### Modellazione solida

### Join of pointsets: esempio

- Fornisco un inseme di punti e il loro join e' il loro guscio convesso
- La seconda figura è il guscio convesso delle prime due
- Si ottiene unendo i punti
- MK trasforma un punto in uno 0-poliedro
- AA significa applied all. Ottengo sempre una lista
- con S=AA(FOIN)... prendo i primi quattro punti di P, dall'elemento 4 a 7 e poi il 7

In [6]:
from pyplasm import *

pts = [[0,0],[.5,0],[0,.5],[.5,.5],[1,.5],[1.5,.5],[1.5,1],[.25,1]] # coords
P = AA(MK)(pts) # 0-polyhedra
S = AA(JOIN)([P[0:4],P[4:7],P[7]]) # array of d-polyhedra
H = JOIN(S) # 2-polyhedron

In [7]:
VIEW(STRUCT(AA(SKELETON(1))(S)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007DDD810> >

![2017-11-03_133023.png](imm/2017-11-03_133023.png)

In [8]:
VIEW(H)

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B6E3D20> >

![2017-11-03_133058.png](imm/2017-11-03_133058.png)

### Simplex: esempio

- le facce dei simplessi sono i sottoinsieme deiloro vertici presi in tutti i modi possibili

In [9]:
s0,s1,s2,s3 = [SIMPLEX(d) for d in range(4)] # array of standard d-simplices
VIEW(s1); VIEW(s2); VIEW(s3);
points = [[1,1,1],[0,1,1],[1,0,0],[1,1,0]] # coords of 4 points
tetra = JOIN(AA(MK)(points)) # 3-simplex
VIEW(tetra)

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007DDD300> >

![2017-11-03_134536.png](imm/2017-11-03_134536.png)

### Simplicial complex: esempio 1

In [10]:
from larlib import * # import LAR library
V,CV = larSimplexGrid1([5,5,5]) # structured simplicial grid
FV = larSimplexFacets(CV) # 2-simplicial grid
EV = larSimplexFacets(FV) # 1-simplicial grid
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,CV))))
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,FV))))
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,EV))))
BV = [FV[t] for t in boundaryCells(CV,FV)] # boundary 2-simplices
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,BV))))

c:\programmi\python27\lib\site-packages\larlib\larstruct.py:233: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self.body = [item for item in data if item != None]


<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B3BF540> >

![2017-11-03_134751.png](imm/2017-11-03_134751.png)

### Simplicial complex: esempio 2

- prima ho genrato una serie di punti random nel cerchio di raggio unitario
- con scipy.spatial ho importato Delaunay
- ho costruito un oggetto passando l'array dei vertici
- l'attributo "verticis" restituisce la lista dei triangoli dati come triple di vertici

In [11]:
from larlib import *; from random import random as rand
points = [[2*PI*rand(),rand()] for k in range(1000)]
V = [[SQRT(r)*COS(alpha),SQRT(r)*SIN(alpha)] for alpha,r in points]
cells = [[k+1] for k,v in enumerate(V)]
VIEW(MKPOL([V,cells,None]))
from scipy.spatial import Delaunay
FV = Delaunay(array(V)).vertices
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,FV))))
VIEW(SKELETON(1)(STRUCT(MKPOLS((V,FV)))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B3BEFC0> >

![2017-11-03_135015.png](imm/2017-11-03_135015.png)

Vediamo il tipo di alcune delle sotto espressioni del codice precedente

- FV è un array shipy di triple di vertici

In [12]:
FV

array([[808, 405, 589],
       [726, 779, 636],
       [779, 726, 859],
       ..., 
       [ 52, 831, 482],
       [391,  52, 482],
       [ 52, 391, 831]])

- è una lista python

In [13]:
V

[[-0.38009169826152794, -0.09061119745682147],
 [-0.6156272570666909, 0.6753707549091393],
 [0.9002501417197958, 0.4008368580579807],
 [-0.12392227590154326, 0.48907429414606035],
 [0.27712303701212804, 0.5917114752991262],
 [0.6645701729399068, -0.430558206186476],
 [-0.7866980431186849, -0.27234486296850435],
 [0.5819963066088683, 0.3132337336777656],
 [-0.7737185661604756, 0.3128402519790061],
 [-0.8031492266904947, 0.40770958797174206],
 [0.3516900328124702, -0.3529383403130207],
 [-0.07095318914356538, -0.3555604475635007],
 [-0.29803755250770403, -0.6022607252904325],
 [-0.6614506333983559, 0.32507206313843295],
 [0.2018654814731007, -0.48477182474984265],
 [-0.5724686204124696, 0.08730883147835657],
 [-0.4875007701018272, -0.6788763805222325],
 [0.3287204452267406, -0.048897325278104274],
 [0.21783507320744605, 0.7366430237762257],
 [-0.08781222491511552, -0.6479461700768626],
 [0.3865902710182225, 0.8036090059758094],
 [-0.42503081656386177, 0.6655961500227805],
 [-0.2010038549

- è una lista di oggetti Hpc

In [14]:
MKPOLS((V,FV))

[<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000B3BE270> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC130C0> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC130F0> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC13120> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC13150> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC13180> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC131B0> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC131E0> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BC13210> >,
 <pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_

- per avere un solo oggetto Hpc devo utilizzare la funzione STRUCT

In [15]:
STRUCT(MKPOLS((V,FV)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007F393F0> >

In [17]:
VIEW(STRUCT(MKPOLS((V,FV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007F513F0> >

![2017-11-03_141402.png](imm/2017-11-03_141402.png)

- EXPLODE è una funzione che allontana gli oggetti geometrici tra loro

In [16]:
EXPLODE(1.2,1.2,1)(MKPOLS((V,FV)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BDC9480> >

In [18]:
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,FV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000BDF84E0> >

![2017-11-03_141500.png](imm/2017-11-03_141500.png)

## Libearia Lar per la rappresentazione di complessi cellulari

- l'import di larlib importa anche pyplasm
- [Repository GutHub lar-cc](https://github.com/cvdlab/lar-cc)

In [20]:
from larlib import *

- LAR model: (V,FV,EV)

In [21]:
V = [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1]]
FV = [[0, 1, 3], [1, 2, 4], [1, 3, 4], [2, 4, 5]]
EV = [[0,1],[0,3],[1,2],[1,3],[1,4],[2,4],[2,5],[3,4],[4,5]]

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007F391B0> >

In [22]:
VIEW(STRUCT(MKPOLS((V,FV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000002AB9C7B0> >

![2017-11-03_143558.png](imm/2017-11-03_143558.png)

In [23]:
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,FV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000002AB9CED0> >

![2017-11-03_143615.png](imm/2017-11-03_143615.png)

In [24]:
VIEW(STRUCT(MKPOLS((V,EV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007F393C0> >

![2017-11-03_143636.png](imm/2017-11-03_143636.png)

In [25]:
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,EV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000007F392A0> >

![2017-11-03_143653.png](imm/2017-11-03_143653.png)

In [26]:
csrFV = csrCreate(FV)
csrEV = csrCreate(EV)
print "\ncsrCreate(FV) =\n", csrFV
print "\n>>> csr2DenseMatrix"
print "\nFV =\n", csr2DenseMatrix(csrFV)
print "\nEV =\n", csr2DenseMatrix(csrEV)


csrCreate(FV) =
  (0, 0)	1
  (0, 1)	1
  (0, 3)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	1
  (3, 2)	1
  (3, 4)	1
  (3, 5)	1

>>> csr2DenseMatrix

FV =
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [0 1 0 1 1 0]
 [0 0 1 0 1 1]]

EV =
[[1 1 0 0 0 0]
 [1 0 0 1 0 0]
 [0 1 1 0 0 0]
 [0 1 0 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 1 0]
 [0 0 1 0 0 1]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]]
